# Generated by Django 3.2.5 on 2021-07-25 08:15
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("market", "0003_auto_20210725_0610")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, verbose_name="slug"),
        )
    ]
